<div id="myCarousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <img class="first-slide" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="First slide">
      <div class="container">
        <div class="carousel-caption">
          <h1><?php echo date("d/m/Y", mktime(0, 0, 0, date("m"), date("d"), date("Y"))); ?> Exports Downloaded <span style="color: green;">Successfully<span></h1>
          <p>
          Export ran on <?php echo date("d/m/Y @ H:i:s", mktime(0, 34, 23, date("m"), date("d"), date("Y"))); ?>.
          Downloaded from Mayden servers on <?php echo date("d/m/Y @ H:i:s", mktime(2, 0, 12, date("m"), date("d"), date("Y"))); ?>
          Finished importing into local system on <?php echo date("d/m/Y @ H:i:s", mktime(2, 22, 43, date("m"), date("d"), date("Y"))); ?>
          </p>
          <p><a class="btn btn-lg btn-primary" href="/log/<?php echo uniqid(); ?>" role="button">View Log</a></p>
        </div>
      </div>
    </div>
    <div class="item">
      <img class="second-slide" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Second slide">
      <div class="container">
        <div class="carousel-caption">
          <h1><?php echo date("d/m/Y", mktime(0, 0, 0, date("m"), date("d")-1, date("Y"))); ?> Exports Downloaded <span style="color: red;">Unsuccessfully<span></h1>
          <p>
          Export ran on <?php echo date("d/m/Y @ H:i:s", mktime(0, 34, 23, date("m"), date("d")-1, date("Y"))); ?>.
          Downloaded from Mayden servers on <?php echo date("d/m/Y @ H:i:s", mktime(2, 0, 12, date("m"), date("d")-1, date("Y"))); ?>
          Finished importing into local system on <?php echo date("d/m/Y @ H:i:s", mktime(2, 22, 43, date("m"), date("d")-1, date("Y"))); ?>
          </p>
          <p><a class="btn btn-lg btn-primary" href="/log/<?php echo uniqid(); ?>" role="button">View Log</a></p>
        </div>
      </div>
    </div>
    <div class="item">
      <img class="third-slide" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Third slide">
      <div class="container">
        <div class="carousel-caption">
          <h1><?php echo date("d/m/Y", mktime(0, 0, 0, date("m"), date("d")-2, date("Y"))); ?> Exports Downloaded <span style="color: green;">Successfully<span></h1>
          <p>
          Export ran on <?php echo date("d/m/Y @ H:i:s", mktime(0, 34, 23, date("m"), date("d")-2, date("Y"))); ?>.
          Downloaded from Mayden servers on <?php echo date("d/m/Y @ H:i:s", mktime(2, 0, 12, date("m"), date("d")-2, date("Y"))); ?>
          Finished importing into local system on <?php echo date("d/m/Y @ H:i:s", mktime(2, 22, 43, date("m"), date("d")-2, date("Y"))); ?>
          </p>
          <p><a class="btn btn-lg btn-primary" href="/log/<?php echo uniqid(); ?>" role="button">View Log</a></p>
        </div>
      </div>
    </div>
  </div>
  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>