<div class="navbar-wrapper">
  <div class="container">

    <nav class="navbar navbar-inverse navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Tohmua / Thoth</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="/">Home</a></li>
            <li><a href="/logs">View Logs</a></li>
            <li><a href="/export-schema">Export Schema</a></li>
            <li><a href="/system-updates">System Updates</a></li>
            <li><a href="#logs">Derived Fields</a></li>
            <li><a href="#support">Support</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">System <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="/run-export">Run Export</a></li>
                <li><a href="#">Check Connection To Server</a></li>
                <li role="separator" class="divider"></li>
                <li class="dropdown-header">Admin</li>
                <li><a href="#">Manage DB Users</a></li>
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </nav>

  </div>
</div>