<!DOCTYPE html>
<html lang="en">
  <?php require __DIR__ . '/sections/head.phtml'; ?>
  <body>
    <?php require __DIR__ . '/sections/nav.phtml'; ?>

    <div class="container marketing">
      <hr class="featurette-divider">
      <table class="table table-hover">
        <thead class="thead-inverse">
          <tr>
            <th>#</th>
            <th>Date</th>
            <th>Time</th>
            <th>Status</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <?php
          foreach(range(50,41) as $id) {
          $uuid = uniqid();
          echo '<tr>
            <th scope="row">' . $uuid . '</th>
            <td>' . date("d/m/Y", mktime(0, $id, 0 - $id, date("m")-2, date("d")+$id, date("Y"))) . '</td>
            <td>' . date("H:i:s", mktime(0, $id, 0 - $id, date("m")-2, date("d")+$id, date("Y"))) . '</td>
            <td style="color:green;">Success</td>
            <td><a href="log/' . $uuid . '">View Log &gt;</a></td>
          </tr>';
          }
          ?>
        </tbody>
      </table>
      <ul class="pagination">
        <li class="active"><a href="#">1</a></li>
        <li><a href="#">2</a></li>
        <li><a href="#">3</a></li>
        <li><a href="#">4</a></li>
        <li><a href="#">5</a></li>
      </ul>

      <hr class="featurette-divider">

      <?php require __DIR__ . '/sections/footer.phtml'; ?>
    </div>
    <?php require __DIR__ . '/sections/foot.phtml'; ?>
  </body>
</html>
