<!DOCTYPE html>
<html lang="en">
  <?php require __DIR__ . '/sections/head.phtml'; ?>
  <body>
    <?php require __DIR__ . '/sections/nav.phtml'; ?>

    <div class="container">
      <hr class="featurette-divider">

      <h1 id="exportStatus">Checking Connection To Server</h1>
      <div class="progress">
        <div id="progressbar" class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 0%;">
          00%
        </div>
      </div>

      <table class="table table-hover">
        <thead class="thead-inverse">
          <tr>
            <th>#</th>
            <th>Date</th>
            <th>Time</th>
            <th>Action</th>
            <th>Status</th>
            <th>Info</th>
          </tr>
        </thead>
        <tbody>
          <?php
          echo '<tr id="row7" style="display:none;">
            <th scope="row">7</th>
            <td>' . date("d/m/Y", mktime(0, 0, 0, date("m"), date("d"), date("Y"))) . '</td>
            <td>' . date("H:i:s", mktime(1, 10, 33, date("m"), date("d"), date("Y"))) . '</td>
            <td>Finished</td>
            <td style="color:green;">info</td>
            <td></td>
          </tr>';
          echo '<tr id="row6" style="display:none;">
            <th scope="row">6</th>
            <td>' . date("d/m/Y", mktime(0, 0, 0, date("m"), date("d"), date("Y"))) . '</td>
            <td>' . date("H:i:s", mktime(0, 53, 21, date("m"), date("d"), date("Y"))) . '</td>
            <td>Importing data</td>
            <td style="color:green;">info</td>
            <td></td>
          </tr>';
          echo '<tr id="row5" style="display:none;">
            <th scope="row">5</th>
            <td>' . date("d/m/Y", mktime(0, 0, 0, date("m"), date("d"), date("Y"))) . '</td>
            <td>' . date("H:i:s", mktime(0, 51, 44, date("m"), date("d"), date("Y"))) . '</td>
            <td>Creating Schema</td>
            <td style="color:green;">info</td>
            <td></td>
          </tr>';
          echo '<tr id="row4" style="display:none;">
            <th scope="row">4</th>
            <td>' . date("d/m/Y", mktime(0, 0, 0, date("m"), date("d"), date("Y"))) . '</td>
            <td>' . date("H:i:s", mktime(0, 49, 56, date("m"), date("d"), date("Y"))) . '</td>
            <td>Parsing Schema</td>
            <td style="color:green;">info</td>
            <td></td>
          </tr>';
          echo '<tr id="row3" style="display:none;">
            <th scope="row">3</th>
            <td>' . date("d/m/Y", mktime(0, 0, 0, date("m"), date("d"), date("Y"))) . '</td>
            <td>' . date("H:i:s", mktime(0, 49, 50, date("m"), date("d"), date("Y"))) . '</td>
            <td>Verifying Download</td>
            <td style="color:green;">info</td>
            <td></td>
          </tr>';
          echo '<tr id="row2" style="display:none;">
            <th scope="row">2</th>
            <td>' . date("d/m/Y", mktime(0, 0, 0, date("m"), date("d"), date("Y"))) . '</td>
            <td>' . date("H:i:s", mktime(0, 21, 34, date("m"), date("d"), date("Y"))) . '</td>
            <td>Downloading Exports</td>
            <td style="color:green;">info</td>
            <td></td>
          </tr>';
          echo '<tr id="row1">
            <th scope="row">1</th>
            <td>' . date("d/m/Y", mktime(0, 0, 0, date("m"), date("d"), date("Y"))) . '</td>
            <td>' . date("H:i:s", mktime(0, 21, 30, date("m"), date("d"), date("Y"))) . '</td>
            <td>Checking Connection To Server</td>
            <td style="color:orange;">warning</td>
            <td>Certificate expires in 30 days</td>
          </tr>';
          ?>
        </tbody>
      </table>

      <hr class="featurette-divider">
      <?php require __DIR__ . '/sections/footer.phtml'; ?>
    </div>
    <?php require __DIR__ . '/sections/foot.phtml'; ?>
    <script>
      window.setTimeout(function(){
        document.getElementById('exportStatus').innerHTML = 'Downloading Exports';
        document.getElementById('progressbar').style.width = '10%';
        document.getElementById('progressbar').innerHTML = '10%';
        document.getElementById('row2').style = 'display: table-row';
      }, 500);
      window.setTimeout(function(){
        document.getElementById('progressbar').style.width = '20%';
        document.getElementById('progressbar').innerHTML = '20%';
      }, 1000);
      window.setTimeout(function(){
        document.getElementById('progressbar').style.width = '30%';
        document.getElementById('progressbar').innerHTML = '30%';
      }, 1500);
      window.setTimeout(function(){
        document.getElementById('progressbar').style.width = '40%';
        document.getElementById('progressbar').innerHTML = '40%';
      }, 2000);
      window.setTimeout(function(){
        document.getElementById('exportStatus').innerHTML = 'Verifying Download';
        document.getElementById('progressbar').style.width = '50%';
        document.getElementById('progressbar').innerHTML = '50%';
        document.getElementById('row3').style = 'display: table-row';
      }, 2500);
      window.setTimeout(function(){
        document.getElementById('exportStatus').innerHTML = 'Parsing Schema';
        document.getElementById('progressbar').style.width = '55%';
        document.getElementById('progressbar').innerHTML = '55%';
        document.getElementById('row4').style = 'display: table-row';
      }, 3000);
      window.setTimeout(function(){
        document.getElementById('exportStatus').innerHTML = 'Creating Schema';
        document.getElementById('progressbar').style.width = '60%';
        document.getElementById('progressbar').innerHTML = '60%';
        document.getElementById('row5').style = 'display: table-row';
      }, 3500);
      window.setTimeout(function(){
        document.getElementById('progressbar').style.width = '70%';
        document.getElementById('progressbar').innerHTML = '70%';
      }, 4000);
      window.setTimeout(function(){
        document.getElementById('progressbar').style.width = '80%';
        document.getElementById('progressbar').innerHTML = '80%';
      }, 4500);
      window.setTimeout(function(){
        document.getElementById('progressbar').style.width = '90%';
        document.getElementById('progressbar').innerHTML = '90%';
      }, 5000);
      window.setTimeout(function(){
        document.getElementById('exportStatus').innerHTML = 'Importing data';
        document.getElementById('progressbar').style.width = '100%';
        document.getElementById('progressbar').innerHTML = '100%';
        document.getElementById('row6').style = 'display: table-row';
      }, 5500);
      window.setTimeout(function(){
        document.getElementById('exportStatus').innerHTML = 'Finished';
        document.getElementById('row7').style = 'display: table-row';
      }, 6000);
    </script>
  </body>
</html>
