<!DOCTYPE html>
<html lang="en">
  <?php require __DIR__ . '/sections/head.phtml'; ?>
  <body>
    <?php require __DIR__ . '/sections/nav.phtml'; ?>

    <div class="container">
      <hr class="featurette-divider">

      <h1 id="updatestatus">Checking For Updates</h1>
      <div class="progress">
        <div id="progressbar" class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 0%;">
          00%
        </div>
      </div>

      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Release v0.1.56</h3>
        </div>
        <div class="panel-body">
          <ul>
            <li>New feature X has been added to the system</li>
            <li>New feature Y has been added to the system</li>
            <li>Bug fixed where clicking on Z will cause the system to crash.</li>
          </ul>
        </div>
      </div>

      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Release v0.1.13</h3>
        </div>
        <div class="panel-body">
          <ul>
            <li>New feature X has been added to the system</li>
            <li>New feature Y has been added to the system</li>
            <li>Bug fixed where clicking on Z will cause the system to crash.</li>
          </ul>
        </div>
      </div>

      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Release v0.1.01</h3>
        </div>
        <div class="panel-body">
          <ul>
            <li>New feature X has been added to the system</li>
            <li>New feature Y has been added to the system</li>
            <li>Bug fixed where clicking on Z will cause the system to crash.</li>
          </ul>
        </div>
      </div>

      <hr class="featurette-divider">
      <?php require __DIR__ . '/sections/footer.phtml'; ?>
    </div>
    <?php require __DIR__ . '/sections/foot.phtml'; ?>
    <script>
      window.setTimeout(function(){
        document.getElementById('progressbar').style.width = '20%';
        document.getElementById('progressbar').innerHTML = '20%';
      }, 1000);
      window.setTimeout(function(){
        document.getElementById('progressbar').style.width = '40%';
        document.getElementById('progressbar').innerHTML = '40%';
      }, 2000);
      window.setTimeout(function(){
        document.getElementById('progressbar').style.width = '60%';
        document.getElementById('progressbar').innerHTML = '60%';
      }, 3000);
      window.setTimeout(function(){
        document.getElementById('progressbar').style.width = '80%';
        document.getElementById('progressbar').innerHTML = '80%';
      }, 4000);
      window.setTimeout(function(){
        document.getElementById('progressbar').style.width = '100%';
        document.getElementById('progressbar').innerHTML = '100%';
      }, 5000);
      window.setTimeout(function(){
        document.getElementById('updatestatus').innerHTML = 'System Up To Date';
      }, 5500);
    </script>
  </body>
</html>
